version: '3.8'

services:
  king-19:
    image: david-19
    build: .
    ports:
      - '7003:7000'
    environment:
      - MONGODB_URI:'mongodb://localhost:27017/Adeebuddin'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
